
--SELECT * FROM  core.table_metadata;
--
--SELECT * FROM dds.ticker;
--SELECT * FROM dds.ticker_price_history;
--SELECT * FROM dds.ticker_dividends_history;
--SELECT * FROM dds.ticker_balance_sheet;

INSERT INTO dds.ticker(
    ticker
    , info
)
SELECT ticker, info
FROM stg.stock_info;

TRUNCATE TABLE dds.ticker_price_history;
INSERT INTO dds.ticker_price_history(
      ticker_id     
    , date        
    , "open"      
    , high        
    , low          
    , "close"       
    , volume
)
SELECT t2.id AS ticker_id
    , t1.date     
    , t1."open"      
    , t1.high        
    , t1.low          
    , t1."close"       
    , t1.volume
FROM stg.stock_history t1
    JOIN dds.ticker t2 USING(ticker);

TRUNCATE TABLE dds.ticker_dividends_history;
INSERT INTO dds.ticker_dividends_history(
    ticker_id
    , date
    , dividends
)
SELECT  t2.id AS ticker_id
        , t1.date::date
        , t1.dividends

FROM stg.stock_dividends_history t1
    JOIN dds.ticker t2 USING(ticker);

TRUNCATE TABLE dds.ticker_balance_sheet;
INSERT INTO dds.ticker_balance_sheet(
                             date,
                             ticker_id, 
                             ordinary_shares_number,
                             share_issued,
                             net_debt,
                             total_debt,
                             tangible_book_value,
                             invested_capital,
                             working_capital,
                             net_tangible_assets,
                             capital_lease_obligations,
                             common_stock_equity,
                             total_capitalization,
                             total_equity_gross_minority_interest,
                             stockholders_equity,
                             gains_losses_not_affecting_retained_earnings,
                             other_equity_adjustments,
                             retained_earnings,
                             capital_stock,
                             common_stock,
                             total_liabilities_net_minority_interest,
                             total_non_current_liabilities_net_minority_interest,
                             other_non_current_liabilities,
                             tradeand_other_payables_non_current,
                             non_current_deferred_liabilities,
                             non_current_deferred_revenue,
                             non_current_deferred_taxes_liabilities,
                             long_term_debt_and_capital_lease_obligation,
                             long_term_capital_lease_obligation,
                             long_term_debt,
                             current_liabilities,
                             other_current_liabilities,
                             current_deferred_liabilities,
                             current_deferred_revenue,
                             current_debt_and_capital_lease_obligation,
                             current_debt,
                             pensionand_other_post_retirement_benefit_plans_current,
                             payables_and_accrued_expenses,
                             payables,
                             total_tax_payable,
                             income_tax_payable,
                             accounts_payable,
                             total_assets,
                             total_non_current_assets,
                             other_non_current_assets,
                             investments_and_advances,
                             long_term_equity_investment,
                             goodwill_and_other_intangible_assets,
                             other_intangible_assets,
                             goodwill,
                             net_ppe,
                             accumulated_depreciation,
                             gross_ppe,
                             leases,
                             other_properties,
                             machinery_furniture_equipment,
                             buildings_and_improvements,
                             land_and_improvements,
                             properties,
                             current_assets,
                             other_current_assets,
                             hedging_assets_current,
                             inventory,
                             finished_goods,
                             work_in_process,
                             raw_materials,
                             receivables,
                             accounts_receivable,
                             allowance_for_doubtful_accounts_receivable,
                             gross_accounts_receivable,
                             cash_cash_equivalents_and_short_term_investments,
                             other_short_term_investments,
                             cash_and_cash_equivalents,
                             cash_equivalents,
                             cash_financial,
                             treasury_shares_number,
                             current_capital_lease_obligation,
                             other_current_borrowings,
                             commercial_paper,
                             non_current_deferred_assets,
                             non_current_deferred_taxes_assets,
                             other_investments,
                             investmentin_financial_assets,
                             available_for_sale_securities,
                             other_receivables,
                             minority_interest,
                             preferred_stock,
                             derivative_product_liabilities,
                             construction_in_progress,
                             prepaid_assets,
                             treasury_stock,
                             additional_paid_in_capital,
                             current_accrued_expenses,
                             inventories_adjustments_allowances,
                             other_inventories,
                             investments_in_other_ventures_under_equity_method,
                             receivables_adjustments_allowances,
                             loans_receivable,
                             employee_benefits,
                             current_provisions,
                             interest_payable,
                             other_payable,
                             non_current_prepaid_assets,
                             preferred_securities_outside_stock_equity,
                             financial_assets,
                             trading_securities,
                             assets_held_for_sale_current,
                             dueto_related_parties_current,
                             duefrom_related_parties_current,
                             non_current_accrued_expenses,
                             long_term_provisions,
                             line_of_credit,
                             taxes_receivable,
                             preferred_shares_number,
                             preferred_stock_equity,
                             held_to_maturity_securities,
                             cash_cash_equivalents_and_federal_funds_sold,
                             liabilities_heldfor_sale_non_current,
                             current_deferred_assets,
                             financial_assets_designatedas_fair_value_through_profitor_loss_total,
                             restricted_cash,
                             other_equity_interest,
                             non_current_pension_and_other_postretirement_benefit_plans,
                             dividends_payable,
                             foreign_currency_translation_adjustments,
                             minimum_pension_liabilities,
                             unrealized_gain_loss,
                             non_current_note_receivables,
                             non_current_accounts_receivable,
                             defined_pension_benefit
)
SELECT 
     t1.date,
     t2.id AS ticker_id,
     ordinary_shares_number,
     share_issued,
     net_debt,
     total_debt,
     tangible_book_value,
     invested_capital,
     working_capital,
     net_tangible_assets,
     capital_lease_obligations,
     common_stock_equity,
     total_capitalization,
     total_equity_gross_minority_interest,
     stockholders_equity,
     gains_losses_not_affecting_retained_earnings,
     other_equity_adjustments,
     retained_earnings,
     capital_stock,
     common_stock,
     total_liabilities_net_minority_interest,
     total_non_current_liabilities_net_minority_interest,
     other_non_current_liabilities,
     tradeand_other_payables_non_current,
     non_current_deferred_liabilities,
     non_current_deferred_revenue,
     non_current_deferred_taxes_liabilities,
     long_term_debt_and_capital_lease_obligation,
     long_term_capital_lease_obligation,
     long_term_debt,
     current_liabilities,
     other_current_liabilities,
     current_deferred_liabilities,
     current_deferred_revenue,
     current_debt_and_capital_lease_obligation,
     current_debt,
     pensionand_other_post_retirement_benefit_plans_current,
     payables_and_accrued_expenses,
     payables,
     total_tax_payable,
     income_tax_payable,
     accounts_payable,
     total_assets,
     total_non_current_assets,
     other_non_current_assets,
     investments_and_advances,
     long_term_equity_investment,
     goodwill_and_other_intangible_assets,
     other_intangible_assets,
     goodwill,
     net_ppe,
     accumulated_depreciation,
     gross_ppe,
     leases,
     other_properties,
     machinery_furniture_equipment,
     buildings_and_improvements,
     land_and_improvements,
     properties,
     current_assets,
     other_current_assets,
     hedging_assets_current,
     inventory,
     finished_goods,
     work_in_process,
     raw_materials,
     receivables,
     accounts_receivable,
     allowance_for_doubtful_accounts_receivable,
     gross_accounts_receivable,
     cash_cash_equivalents_and_short_term_investments,
     other_short_term_investments,
     cash_and_cash_equivalents,
     cash_equivalents,
     cash_financial,
     treasury_shares_number,
     current_capital_lease_obligation,
     other_current_borrowings,
     commercial_paper,
     non_current_deferred_assets,
     non_current_deferred_taxes_assets,
     other_investments,
     investmentin_financial_assets,
     available_for_sale_securities,
     other_receivables,
     minority_interest,
     preferred_stock,
     derivative_product_liabilities,
     construction_in_progress,
     prepaid_assets,
     treasury_stock,
     additional_paid_in_capital,
     current_accrued_expenses,
     inventories_adjustments_allowances,
     other_inventories,
     investments_in_other_ventures_under_equity_method,
     receivables_adjustments_allowances,
     loans_receivable,
     employee_benefits,
     current_provisions,
     interest_payable,
     other_payable,
     non_current_prepaid_assets,
     preferred_securities_outside_stock_equity,
     financial_assets,
     trading_securities,
     assets_held_for_sale_current,
     dueto_related_parties_current,
     duefrom_related_parties_current,
     non_current_accrued_expenses,
     long_term_provisions,
     line_of_credit,
     taxes_receivable,
     preferred_shares_number,
     preferred_stock_equity,
     held_to_maturity_securities,
     cash_cash_equivalents_and_federal_funds_sold,
     liabilities_heldfor_sale_non_current,
     current_deferred_assets,
     financial_assets_designatedas_fair_value_through_profitor_loss_total,
     restricted_cash,
     other_equity_interest,
     non_current_pension_and_other_postretirement_benefit_plans,
     dividends_payable,
     foreign_currency_translation_adjustments,
     minimum_pension_liabilities,
     unrealized_gain_loss,
     non_current_note_receivables,
     non_current_accounts_receivable,
     defined_pension_benefit
FROM stg.stock_balance_sheet t1
    JOIN dds.ticker t2 USING(ticker);

